export type KosenRegion =
  | "北海道"
  | "東北"
  | "関東信越"
  | "東海"
  | "北陸"
  | "近畿"
  | "中国"
  | "四国"
  | "九州沖縄";

export type KosenType = "national" | "public" | "private";

export interface KosenSchool {
  id: string;
  name: string;
  shortName: string;
  region: KosenRegion;
  type: KosenType;
  prefecture: string;
  /** Primary focus tags for grant matching. */
  strengths: string[];
  /** Placeholder payout address / account label for MVP. */
  payoutLabel: string;
}

/**
 * Representative registry of Japanese KOSEN (高等専門学校).
 * IDs are stable keys for FundOS recipient routing.
 */
export const KOSEN_REGISTRY: readonly KosenSchool[] = [
  {
    id: "kosen_hakodate",
    name: "函館工業高等専門学校",
    shortName: "函館高専",
    region: "北海道",
    type: "national",
    prefecture: "北海道",
    strengths: ["marine", "info", "equipment"],
    payoutLabel: "函館高専・教育研究支援口",
  },
  {
    id: "kosen_tomakomai",
    name: "苫小牧工業高等専門学校",
    shortName: "苫小牧高専",
    region: "北海道",
    type: "national",
    prefecture: "北海道",
    strengths: ["mechanical", "equipment"],
    payoutLabel: "苫小牧高専・教育研究支援口",
  },
  {
    id: "kosen_asahikawa",
    name: "旭川工業高等専門学校",
    shortName: "旭川高専",
    region: "北海道",
    type: "national",
    prefecture: "北海道",
    strengths: ["chemistry", "research"],
    payoutLabel: "旭川高専・教育研究支援口",
  },
  {
    id: "kosen_kushiro",
    name: "釧路工業高等専門学校",
    shortName: "釧路高専",
    region: "北海道",
    type: "national",
    prefecture: "北海道",
    strengths: ["electrical", "equipment"],
    payoutLabel: "釧路高専・教育研究支援口",
  },
  {
    id: "kosen_hachinohe",
    name: "八戸工業高等専門学校",
    shortName: "八戸高専",
    region: "東北",
    type: "national",
    prefecture: "青森県",
    strengths: ["mechanical", "equipment"],
    payoutLabel: "八戸高専・教育研究支援口",
  },
  {
    id: "kosen_ichinoseki",
    name: "一関工業高等専門学校",
    shortName: "一関高専",
    region: "東北",
    type: "national",
    prefecture: "岩手県",
    strengths: ["materials", "research"],
    payoutLabel: "一関高専・教育研究支援口",
  },
  {
    id: "kosen_sendai",
    name: "仙台高等専門学校",
    shortName: "仙台高専",
    region: "東北",
    type: "national",
    prefecture: "宮城県",
    strengths: ["info", "robotics", "equipment"],
    payoutLabel: "仙台高専・教育研究支援口",
  },
  {
    id: "kosen_akita",
    name: "秋田工業高等専門学校",
    shortName: "秋田高専",
    region: "東北",
    type: "national",
    prefecture: "秋田県",
    strengths: ["materials", "research"],
    payoutLabel: "秋田高専・教育研究支援口",
  },
  {
    id: "kosen_tsuruoka",
    name: "鶴岡工業高等専門学校",
    shortName: "鶴岡高専",
    region: "東北",
    type: "national",
    prefecture: "山形県",
    strengths: ["bio", "research", "scholarship"],
    payoutLabel: "鶴岡高専・教育研究支援口",
  },
  {
    id: "kosen_fukushima",
    name: "福島工業高等専門学校",
    shortName: "福島高専",
    region: "東北",
    type: "national",
    prefecture: "福島県",
    strengths: ["nuclear", "equipment", "research"],
    payoutLabel: "福島高専・教育研究支援口",
  },
  {
    id: "kosen_ibaraki",
    name: "茨城工業高等専門学校",
    shortName: "茨城高専",
    region: "関東信越",
    type: "national",
    prefecture: "茨城県",
    strengths: ["electrical", "equipment"],
    payoutLabel: "茨城高専・教育研究支援口",
  },
  {
    id: "kosen_oyama",
    name: "小山工業高等専門学校",
    shortName: "小山高専",
    region: "関東信越",
    type: "national",
    prefecture: "栃木県",
    strengths: ["mechanical", "equipment"],
    payoutLabel: "小山高専・教育研究支援口",
  },
  {
    id: "kosen_gunma",
    name: "群馬工業高等専門学校",
    shortName: "群馬高専",
    region: "関東信越",
    type: "national",
    prefecture: "群馬県",
    strengths: ["chemistry", "research"],
    payoutLabel: "群馬高専・教育研究支援口",
  },
  {
    id: "kosen_kisarazu",
    name: "木更津工業高等専門学校",
    shortName: "木更津高専",
    region: "関東信越",
    type: "national",
    prefecture: "千葉県",
    strengths: ["info", "equipment"],
    payoutLabel: "木更津高専・教育研究支援口",
  },
  {
    id: "kosen_tokyo",
    name: "東京工業高等専門学校",
    shortName: "東京高専",
    region: "関東信越",
    type: "national",
    prefecture: "東京都",
    strengths: ["robotics", "info", "equipment", "scholarship"],
    payoutLabel: "東京高専・教育研究支援口",
  },
  {
    id: "kosen_nagaoka",
    name: "長岡工業高等専門学校",
    shortName: "長岡高専",
    region: "関東信越",
    type: "national",
    prefecture: "新潟県",
    strengths: ["materials", "research", "equipment"],
    payoutLabel: "長岡高専・教育研究支援口",
  },
  {
    id: "kosen_nagano",
    name: "長野工業高等専門学校",
    shortName: "長野高専",
    region: "関東信越",
    type: "national",
    prefecture: "長野県",
    strengths: ["electrical", "equipment"],
    payoutLabel: "長野高専・教育研究支援口",
  },
  {
    id: "kosen_ishikawa",
    name: "石川工業高等専門学校",
    shortName: "石川高専",
    region: "北陸",
    type: "national",
    prefecture: "石川県",
    strengths: ["mechanical", "equipment"],
    payoutLabel: "石川高専・教育研究支援口",
  },
  {
    id: "kosen_toyama",
    name: "富山高等専門学校",
    shortName: "富山高専",
    region: "北陸",
    type: "national",
    prefecture: "富山県",
    strengths: ["marine", "info", "equipment"],
    payoutLabel: "富山高専・教育研究支援口",
  },
  {
    id: "kosen_fukui",
    name: "福井工業高等専門学校",
    shortName: "福井高専",
    region: "北陸",
    type: "national",
    prefecture: "福井県",
    strengths: ["electrical", "research"],
    payoutLabel: "福井高専・教育研究支援口",
  },
  {
    id: "kosen_gifu",
    name: "岐阜工業高等専門学校",
    shortName: "岐阜高専",
    region: "東海",
    type: "national",
    prefecture: "岐阜県",
    strengths: ["architecture", "equipment"],
    payoutLabel: "岐阜高専・教育研究支援口",
  },
  {
    id: "kosen_numazu",
    name: "沼津工業高等専門学校",
    shortName: "沼津高専",
    region: "東海",
    type: "national",
    prefecture: "静岡県",
    strengths: ["mechanical", "robotics", "equipment"],
    payoutLabel: "沼津高専・教育研究支援口",
  },
  {
    id: "kosen_toyota",
    name: "豊田工業高等専門学校",
    shortName: "豊田高専",
    region: "東海",
    type: "national",
    prefecture: "愛知県",
    strengths: ["mechanical", "robotics", "equipment", "scholarship"],
    payoutLabel: "豊田高専・教育研究支援口",
  },
  {
    id: "kosen_suzuka",
    name: "鈴鹿工業高等専門学校",
    shortName: "鈴鹿高専",
    region: "東海",
    type: "national",
    prefecture: "三重県",
    strengths: ["chemistry", "bio", "research"],
    payoutLabel: "鈴鹿高専・教育研究支援口",
  },
  {
    id: "kosen_maizuru",
    name: "舞鶴工業高等専門学校",
    shortName: "舞鶴高専",
    region: "近畿",
    type: "national",
    prefecture: "京都府",
    strengths: ["marine", "electrical", "equipment"],
    payoutLabel: "舞鶴高専・教育研究支援口",
  },
  {
    id: "kosen_akashi",
    name: "明石工業高等専門学校",
    shortName: "明石高専",
    region: "近畿",
    type: "national",
    prefecture: "兵庫県",
    strengths: ["architecture", "urban", "equipment"],
    payoutLabel: "明石高専・教育研究支援口",
  },
  {
    id: "kosen_nara",
    name: "奈良工業高等専門学校",
    shortName: "奈良高専",
    region: "近畿",
    type: "national",
    prefecture: "奈良県",
    strengths: ["info", "electrical", "equipment"],
    payoutLabel: "奈良高専・教育研究支援口",
  },
  {
    id: "kosen_wakayama",
    name: "和歌山工業高等専門学校",
    shortName: "和歌山高専",
    region: "近畿",
    type: "national",
    prefecture: "和歌山県",
    strengths: ["bio", "chemistry", "research"],
    payoutLabel: "和歌山高専・教育研究支援口",
  },
  {
    id: "kosen_yonago",
    name: "米子工業高等専門学校",
    shortName: "米子高専",
    region: "中国",
    type: "national",
    prefecture: "鳥取県",
    strengths: ["electrical", "equipment"],
    payoutLabel: "米子高専・教育研究支援口",
  },
  {
    id: "kosen_matsue",
    name: "松江工業高等専門学校",
    shortName: "松江高専",
    region: "中国",
    type: "national",
    prefecture: "島根県",
    strengths: ["info", "equipment"],
    payoutLabel: "松江高専・教育研究支援口",
  },
  {
    id: "kosen_tsuyama",
    name: "津山工業高等専門学校",
    shortName: "津山高専",
    region: "中国",
    type: "national",
    prefecture: "岡山県",
    strengths: ["mechanical", "equipment"],
    payoutLabel: "津山高専・教育研究支援口",
  },
  {
    id: "kosen_hiroshima",
    name: "広島商船高等専門学校",
    shortName: "広島商船高専",
    region: "中国",
    type: "national",
    prefecture: "広島県",
    strengths: ["marine", "equipment"],
    payoutLabel: "広島商船高専・教育研究支援口",
  },
  {
    id: "kosen_kure",
    name: "呉工業高等専門学校",
    shortName: "呉高専",
    region: "中国",
    type: "national",
    prefecture: "広島県",
    strengths: ["mechanical", "equipment", "scholarship"],
    payoutLabel: "呉高専・教育研究支援口",
  },
  {
    id: "kosen_tokuyama",
    name: "徳山工業高等専門学校",
    shortName: "徳山高専",
    region: "中国",
    type: "national",
    prefecture: "山口県",
    strengths: ["chemistry", "research"],
    payoutLabel: "徳山高専・教育研究支援口",
  },
  {
    id: "kosen_ube",
    name: "宇部工業高等専門学校",
    shortName: "宇部高専",
    region: "中国",
    type: "national",
    prefecture: "山口県",
    strengths: ["materials", "research", "equipment"],
    payoutLabel: "宇部高専・教育研究支援口",
  },
  {
    id: "kosen_ochi",
    name: "大島商船高等専門学校",
    shortName: "大島商船高専",
    region: "中国",
    type: "national",
    prefecture: "山口県",
    strengths: ["marine", "equipment"],
    payoutLabel: "大島商船高専・教育研究支援口",
  },
  {
    id: "kosen_takamatsu",
    name: "香川高等専門学校",
    shortName: "香川高専",
    region: "四国",
    type: "national",
    prefecture: "香川県",
    strengths: ["info", "mechanical", "equipment"],
    payoutLabel: "香川高専・教育研究支援口",
  },
  {
    id: "kosen_niihama",
    name: "新居浜工業高等専門学校",
    shortName: "新居浜高専",
    region: "四国",
    type: "national",
    prefecture: "愛媛県",
    strengths: ["chemistry", "equipment"],
    payoutLabel: "新居浜高専・教育研究支援口",
  },
  {
    id: "kosen_yuge",
    name: "弓削商船高等専門学校",
    shortName: "弓削商船高専",
    region: "四国",
    type: "national",
    prefecture: "愛媛県",
    strengths: ["marine", "equipment"],
    payoutLabel: "弓削商船高専・教育研究支援口",
  },
  {
    id: "kosen_kochi",
    name: "高知工業高等専門学校",
    shortName: "高知高専",
    region: "四国",
    type: "national",
    prefecture: "高知県",
    strengths: ["social", "equipment", "scholarship"],
    payoutLabel: "高知高専・教育研究支援口",
  },
  {
    id: "kosen_kurume",
    name: "久留米工業高等専門学校",
    shortName: "久留米高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "福岡県",
    strengths: ["mechanical", "equipment"],
    payoutLabel: "久留米高専・教育研究支援口",
  },
  {
    id: "kosen_ariake",
    name: "有明工業高等専門学校",
    shortName: "有明高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "福岡県",
    strengths: ["energy", "equipment", "research"],
    payoutLabel: "有明高専・教育研究支援口",
  },
  {
    id: "kosen_kitakyushu",
    name: "北九州工業高等専門学校",
    shortName: "北九州高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "福岡県",
    strengths: ["production", "equipment", "scholarship"],
    payoutLabel: "北九州高専・教育研究支援口",
  },
  {
    id: "kosen_sasebo",
    name: "佐世保工業高等専門学校",
    shortName: "佐世保高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "長崎県",
    strengths: ["mechanical", "marine", "equipment"],
    payoutLabel: "佐世保高専・教育研究支援口",
  },
  {
    id: "kosen_kumamoto",
    name: "熊本高等専門学校",
    shortName: "熊本高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "熊本県",
    strengths: ["info", "bio", "equipment", "research"],
    payoutLabel: "熊本高専・教育研究支援口",
  },
  {
    id: "kosen_oita",
    name: "大分工業高等専門学校",
    shortName: "大分高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "大分県",
    strengths: ["electrical", "equipment"],
    payoutLabel: "大分高専・教育研究支援口",
  },
  {
    id: "kosen_miyakonojo",
    name: "都城工業高等専門学校",
    shortName: "都城高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "宮崎県",
    strengths: ["materials", "architecture", "equipment"],
    payoutLabel: "都城高専・教育研究支援口",
  },
  {
    id: "kosen_kagoshima",
    name: "鹿児島工業高等専門学校",
    shortName: "鹿児島高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "鹿児島県",
    strengths: ["electrical", "info", "equipment"],
    payoutLabel: "鹿児島高専・教育研究支援口",
  },
  {
    id: "kosen_okinawa",
    name: "沖縄工業高等専門学校",
    shortName: "沖縄高専",
    region: "九州沖縄",
    type: "national",
    prefecture: "沖縄県",
    strengths: ["info", "bio", "scholarship", "equipment"],
    payoutLabel: "沖縄高専・教育研究支援口",
  },
] as const;

export function getKosen(id: string): KosenSchool | undefined {
  return KOSEN_REGISTRY.find((k) => k.id === id);
}

export function listKosen(filter?: {
  region?: KosenRegion;
  type?: KosenType;
  strength?: string;
}): KosenSchool[] {
  return KOSEN_REGISTRY.filter((k) => {
    if (filter?.region && k.region !== filter.region) return false;
    if (filter?.type && k.type !== filter.type) return false;
    if (filter?.strength && !k.strengths.includes(filter.strength)) return false;
    return true;
  });
}
